name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # allow GITHUB_TOKEN to publish packages
      id-token: write # The OIDC ID token is used for authentication with JSR.
    steps:
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - uses: actions/checkout@v4

      - run: bunx jsr publish
      - run: bunx --bun npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
