name: "Validate"

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - uses: actions/checkout@v4

      - run: bun install
      - run: bun run lint
      - run: bun run tsc
      - run: bun run test
